"""
Resources module for RivalSearchMCP.
Provides actual data sources and persistent storage for MCP clients.
Following FastMCP specification with proper annotations and decorators.
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
from fastmcp import FastMCP
from fastmcp.server.dependencies import get_context

# Create data directories
DATA_DIR = Path.home() / ".rivalsearch" / "data"
CACHE_DIR = DATA_DIR / "cache"
EXPORTS_DIR = DATA_DIR / "exports"
DB_DIR = DATA_DIR / "db"

for dir_path in [DATA_DIR, CACHE_DIR, EXPORTS_DIR, DB_DIR]:
    dir_path.mkdir(parents=True, exist_ok=True)


def register_resources(mcp: FastMCP):
    """Register proper MCP resources following FastMCP specification."""

    @mcp.resource(
        "file://cached/searches/{query_hash}.json",
        name="Cached Search Results",
        description="Persistent cache of web search results in JSON format",
        mime_type="application/json",
        annotations={
            "audience": ["user"],
        },
    )
    def get_cached_search_results(query_hash: str) -> str:
        """Access cached web search results by query hash."""
        cache_file = CACHE_DIR / "searches" / f"{query_hash}.json"
        if cache_file.exists():
            return cache_file.read_text()
        return json.dumps({"error": "Cache not found", "query_hash": query_hash})

    @mcp.resource(
        "db://trends/data/{table_name}",
        name="Trends Data Tables",
        description="SQLite database tables containing Google Trends data",
        mime_type="application/x-sqlite3",
        annotations={
            "audience": ["user"],
        },
    )
    def get_trends_database(table_name: str) -> bytes:
        """Access trends data stored in SQLite database tables."""
        db_file = DB_DIR / "trends.db"
        if db_file.exists():
            return db_file.read_bytes()
        return json.dumps({"error": "Database not found"}).encode()

    @mcp.resource(
        "file://exports/{filename}",
        name="Exported Data Files",
        description="Data export files (CSV, JSON, SQL) generated by tools",
        annotations={
            "audience": ["user"],
        },
    )
    def get_exported_files(filename: str) -> str:
        """Access exported data files generated by export tools."""
        export_file = EXPORTS_DIR / filename
        if export_file.exists():
            if filename.endswith(".json"):
                return export_file.read_text()
            elif filename.endswith(".csv"):
                return f"CSV file available at: {export_file}"
            else:
                return f"File available at: {export_file}"
        return json.dumps({"error": "Export file not found", "filename": filename})

    @mcp.resource(
        "api://google/trends/live",
        name="Live Google Trends API",
        description="Direct access to Google Trends API data streams",
        mime_type="application/json",
        annotations={
            "audience": ["user"],
        },
    )
    def get_live_trends_data() -> str:
        """Access live Google Trends data (cached for performance)."""
        # Return cached live data or fetch fresh
        cache_file = CACHE_DIR / "live_trends.json"
        if (
            cache_file.exists()
            and (datetime.now().timestamp() - cache_file.stat().st_mtime) < 3600
        ):  # 1 hour cache
            return cache_file.read_text()

        # This would normally fetch from Google Trends API
        live_data = {
            "timestamp": datetime.now().isoformat(),
            "trending_searches": ["AI", "Machine Learning", "Web Development"],
            "source": "Google Trends API",
            "cached": True,
        }
        cache_file.write_text(json.dumps(live_data, indent=2))
        return json.dumps(live_data, indent=2)

    @mcp.resource(
        "file://config/server.json",
        name="Server Configuration",
        description="Current server configuration and capabilities",
        mime_type="application/json",
        annotations={
            "audience": ["user"],
        },
    )
    def get_server_config() -> str:
        """Access server configuration as a data resource."""
        config = {
            "name": "RivalSearchMCP",
            "version": "2.0.0",
            "environment": os.getenv("ENVIRONMENT", "development"),
            "capabilities": [
                "web_search",
                "content_operations",
                "traverse_website",
                "trends_core",
                "trends_export",
                "research_topic",
                "scientific_research",
            ],
            "data_directories": {
                "cache": str(CACHE_DIR),
                "exports": str(EXPORTS_DIR),
                "database": str(DB_DIR),
            },
            "features": {
                "cloudflare_bypass": True,
                "ocr_support": True,
                "ai_analysis": True,
                "data_caching": True,
                "export_formats": ["csv", "json", "sql"],
            },
            "timestamp": datetime.now().isoformat(),
        }
        return json.dumps(config, indent=2)

    @mcp.resource(
        "stream://performance/metrics",
        name="Performance Metrics Stream",
        description="Real-time performance metrics and statistics",
        mime_type="application/json",
        annotations={
            "audience": ["user"],
        },
    )
    def get_performance_metrics() -> str:
        """Stream current performance metrics."""
        metrics = {
            "timestamp": datetime.now().isoformat(),
            "uptime_seconds": 0,  # Would be calculated
            "total_requests": 0,  # Would be tracked
            "active_connections": 0,
            "memory_usage_mb": 0,  # Would be measured
            "cache_size_mb": sum(
                f.stat().st_size for f in CACHE_DIR.rglob("*") if f.is_file()
            )
            / (1024 * 1024),
            "export_files_count": len(list(EXPORTS_DIR.glob("*"))),
            "status": "operational",
        }
        return json.dumps(metrics, indent=2)

    @mcp.resource(
        "file://logs/server.log",
        name="Server Logs",
        description="Application logs for debugging and monitoring",
        mime_type="text/plain",
        annotations={
            "audience": ["user"],
        },
    )
    def get_server_logs() -> str:
        """Access server log files."""
        log_file = DATA_DIR / "server.log"
        if log_file.exists():
            return log_file.read_text()
        return "No logs available"

    @mcp.resource(
        "db://research/history",
        name="Research Workflow History",
        description="Database of completed research workflows and results",
        mime_type="application/x-sqlite3",
        annotations={
            "audience": ["user"],
        },
    )
    def get_research_history() -> bytes:
        """Access research workflow history database."""
        db_file = DB_DIR / "research.db"
        if db_file.exists():
            return db_file.read_bytes()
        return json.dumps({"error": "Research history database not found"}).encode()
